PROJETO/Agenda/Agenda/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Agenda.Models
{
    public class Categoria
    {
        public int categoriaID { get; set; }
        public string categoriaDescricao { get; set; }
        public DateTime categoriaDtCadastro { get; set; }
    }
}

PROJETO/Agenda/Agenda/Models/ListaAgenda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Agenda.Models
{
    public class ListaAgenda
    {
        public int agendaId { get; set; }
        public string agendaTitulo { get; set; }
        public string agendaDescricao { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public string agendaData { get; set; }
        public string evento { get; set; }
        public string categoria { get; set; }
    }
}

PROJETO/Agenda/Agenda/Controllers/CategoriaController.cs
using Agenda.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agenda.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Categoria/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Inserir(Categoria categoria)
        {
            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();

            // chamada da procedure passando os parametros
            SqlCommand Command = new SqlCommand("[dbo].[sp_Categoria_Inserir]", conn);
            Command.CommandType = CommandType.StoredProcedure;
            Command.Parameters.AddWithValue("@CategoriaDescricao", categoria.categoriaDescricao);
            Command.Parameters.AddWithValue("@categoriaDtCadastro", categoria.categoriaDtCadastro);

            var param = Command.Parameters.Add("@saida", SqlDbType.VarChar, 300);
            param.Direction = ParameterDirection.Output;

            var inserido = Command.ExecuteNonQuery();

            string result = param.Value.ToString().Trim();
            // return RedirectToAction("Index", "Home");

            ViewBag.Message = result;
            return View();

        }

        public ActionResult _Buscar()
        {
            // chamo  a conexao 
            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();
            DataTable dataTable = new DataTable();

            // chamada da procedure passando os parametros
            SqlCommand Command = new SqlCommand("[dbo].[sp_Categoria_buscar]", conn);
            Command.CommandType = CommandType.StoredProcedure;

            var param = Command.Parameters.Add("@saida", SqlDbType.VarChar, 300);
            param.Direction = ParameterDirection.Output;

            // preencho data table e retorno a partialview os dados dele
            using (SqlDataAdapter da = new SqlDataAdapter(Command))
            {
                da.Fill(dataTable);
            }

            var result = Command.ExecuteNonQuery();
            conn.Close();

            //essa sessão eu utilizo na partial view para iterar e montar a tabela com essas informações
            Session["CategoriaLista"] = dataTable;
            return PartialView(dataTable);
        }
    }
}

PROJETO/Agenda/Agenda/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Agenda.Models;


namespace Agenda.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult _Listar(string agendaListar)
        {
            // chamo  a conexao 
            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();
            DataTable dataTable = new DataTable();

            // instancio o objeto para desserializar o json que veio via ajax da view
            ListaAgenda agenda = new ListaAgenda();

            // recebo a informação do parametro e uso como entrada no parametro da procedure
            agenda = JsonConvert.DeserializeObject<ListaAgenda>(agendaListar);

            // chamada da procedure passando os parametros
            SqlCommand Command = new SqlCommand("[dbo].[sp_Agenda_filtrar]", conn);
            Command.CommandType = CommandType.StoredProcedure;
            Command.Parameters.AddWithValue("@evento", agenda.evento);

            // preencho data table e retorno a partialview os dados dele
            using (SqlDataAdapter da = new SqlDataAdapter(Command))
            {
                da.Fill(dataTable);
            }

            var result = Command.ExecuteNonQuery();
            conn.Close();

            //essa sessão eu utilizo na partial view para iterar e montar a tabela com essas informações
            Session["AgendaLista"] = dataTable;
          
            return PartialView(dataTable);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {

            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();
            DataTable dataTable = new DataTable();
            // chamada da procedure passando os parametros
            SqlCommand Command = new SqlCommand("[dbo].[sp_PopularCategoriaCombo]", conn);
            Command.CommandType = CommandType.StoredProcedure;

            // preencho data table e retorno a partialview os dados dele
            using (SqlDataAdapter da = new SqlDataAdapter(Command))
            {
                da.Fill(dataTable);
            }

            var result = Command.ExecuteNonQuery();
            conn.Close();

            //essa sessão eu utilizo na partial view para iterar e montar a tabela com essas informações
            ViewBag.Combo = dataTable;

            return View();
           
        }

        [HttpPost]
        public ActionResult Cadastrar(ListaAgenda listaAgenda)
        {
            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();

            // chamada da procedure passando os parametros
            SqlCommand Command = new SqlCommand("[dbo].[sp_Agenda_Inserir]", conn);
            Command.CommandType = CommandType.StoredProcedure;
            Command.Parameters.AddWithValue("@agendaTitulo", listaAgenda.agendaTitulo);
            Command.Parameters.AddWithValue("@agendaDescricao", listaAgenda.agendaDescricao);
            Command.Parameters.AddWithValue("@agendaData", Convert.ToDateTime(listaAgenda.agendaData));
            Command.Parameters.AddWithValue("@agendaCategoria", listaAgenda.categoria);

            var param = Command.Parameters.Add("@saida", SqlDbType.VarChar, 300);
            param.Direction = ParameterDirection.Output;

            var inserido = Command.ExecuteNonQuery();

            string result = param.Value.ToString().Trim();
            return RedirectToAction("Listar", "Home");
        }

        public string Deletar(int Id)
        {
            // chamada da conexao
            ClassConexao.ConexaoDB conexao = new ClassConexao.ConexaoDB();
            SqlConnection conn = conexao.Conectar();

            // passando parametro para a procedure
            SqlCommand Command = new SqlCommand("[dbo].[sp_Agenda_Excluir]", conn);
            Command.CommandType = CommandType.StoredProcedure;
            Command.Parameters.AddWithValue("@agendaId", Id);

            // retorno de saida 
            var param = Command.Parameters.Add("@saida", SqlDbType.VarChar, 300);
            param.Direction = ParameterDirection.Output;

            var deletado = Command.ExecuteNonQuery();

            string result = param.Value.ToString().Trim();

            conn.Close();

            // RETORNO UMA STRING DE SAIDA EM CASO DE ERRO OU ID DA NOTA EM CASO DE SUCESSO
            return result;
        }
    }
}

PROJETO/Agenda/Agenda/Views/Categoria/Inserir.cshtml
@model Agenda.Models.Categoria

@{
    ViewBag.Title = "Cadastrar Categoria";
}

<h2></h2>

@if (ViewBag.Message != null)
{
    <script>

        $(document).ready(function () {

            alert('@ViewBag.Message');

        });

    </script>

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Cadastrar Categoria</h2>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.categoriaDescricao, "Descrição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.categoriaDescricao, new { @class = "form-control", required = "required", title = "Campo Obrigatório" })
                @Html.ValidationMessageFor(model => model.categoriaDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoriaDtCadastro, "Data", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.categoriaDtCadastro, new { @type = "DATE", @class = "form-control", required = "required", title = "Campo Obrigatório" })
                @Html.ValidationMessageFor(model => model.categoriaDtCadastro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inserir" class="btn btn-primary" onclick="PersquisarCategoria()" />
            </div>
        </div>
    </div>
}
<br />

<div id="_tableLista">

</div>

<div>
    @*@Html.ActionLink("Voltar", "Inserir")*@
    @Html.ActionLink("Voltar", "Index", "Home", null, null)
</div>

<script>
    PersquisarCategoria();
    function PersquisarCategoria() {
        $.ajax({
            url: '@Url.Action("_Buscar", "Categoria")',
            data: {},
            dataType: "text",
            type: 'POST',
            async: true,
            success: function (data) {
                $('#_tableLista').html(data);
            }
        });

    }
</script>

PROJETO/Agenda/Agenda/Views/Categoria/_Buscar.cshtml
@{
    System.Data.DataTable dt = (System.Data.DataTable)Session["CategoriaLista"];
}

<div class="table table-responsive">
    <table class="table table-hover table-striped">
        <thead>
            <tr style="color: white; background-color:#1f8bb1; font: bold">
                <th class="text-left">Código Categoria</th>
                <th class="text-left">Descrição Categoria</th>
                <th class="text-left">Data Cadastro</th>
            </tr>
        </thead>

        <tbody id="resultadoTabelaCat">

            @foreach (System.Data.DataRow row in dt.Rows)
            {
                //DataRow row in dt.Rows
                <tr style="line-height:25px;">
                    <td>@row["categoriaId"].ToString()</td>
                    <td>@row["categoriaDescricao"].ToString()</td>
                    <td>@row["categoriaDtCadastro"].ToString()</td>
                </tr>
            }

        </tbody>
    </table>
</div>

PROJETO/Agenda/Agenda/Views/Home/Cadastrar.cshtml
@model Agenda.Models.ListaAgenda

@{
    ViewBag.Title = "Cadastrar Agendamento";
}

<h2><strong>Cadastrar um Novo Agendamento</strong></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.agendaTitulo, "Título", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.agendaTitulo, new { @class = "form-control", required = "required", title = "Campo Obrigatório" })
                @Html.ValidationMessageFor(model => model.agendaTitulo, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.agendaDescricao, "Descrição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.agendaDescricao, new { @class = "form-control", required = "required", title = "Campo Obrigatório" })
                @Html.ValidationMessageFor(model => model.agendaDescricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.agendaData, "Data", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.agendaData, new { @type = "datetime-local", @class = "form-control", required = "required", title = "Campo Obrigatório" })
                @Html.ValidationMessageFor(model => model.agendaData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            @{
    System.Data.DataTable dt = ViewBag.Combo;

    var itens = new List<Agenda.Models.Categoria>();
    itens.Insert(0, null);
    foreach (System.Data.DataRow row in dt.Rows)
    {
        var item = new Agenda.Models.Categoria { categoriaID = Convert.ToInt32(@row["categoriaId"]), categoriaDescricao = @row["categoriaDescricao"].ToString() };
        itens.Add(item);
    };

    @Html.LabelFor(model => model.categoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
                
                    @Html.DropDownList("Categoria", new SelectList(itens, "categoriaID", "categoriaDescricao"), new { @class = "form-control", required = "required", title = "Campo Obrigatório" })
                    @Html.ValidationMessageFor(model => model.categoria, "", new { @class = "text-danger" })
               
            }

        </div>

        <div class="form-group jumboMargin">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-primary form-group" type="submit" value="Inserir" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

PROJETO/Agenda/Agenda/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Principal";
}

<div class="row jumboMargin">
    <div class="jumbotron jumboText">
        <img src="~/Images/evento.png" class="img-responsive" />
    </div>
</div>
@*<div class="row" style="margin-left:35%;margin-right:35%; margin-bottom:0;margin-top:0">
    <img src="~/Images/agenda.png" width="350" height="350" class="img-responsive" />
</div>*@

PROJETO/Agenda/Agenda/Views/Home/Listar.cshtml
@{
    ViewBag.Title = "Lista de Agendamentos Realizados";
}

<h2><strong>Relação de Agendamentos Cadastrados</strong></h2>
<hr />
<form class="form-horizontal">

    <div class="row">
        <div class="col-lg-12">

        </div>
    </div>

    <div class="row">

        <div class="col-lg-2">
            <label for="cbPesquisa">&nbsp</label>
            <select id="cbPesquisa" class="form-control">
                <option>SELECIONE</option>
                <option>PASSADO</option>
                <option>HOJE</option>
                <option>FUTURO</option>
            </select>
        </div>

        <div class="col-lg-1 col-md-1">
            <label for="btnPesquisar">&nbsp</label>
            <button id="btnPesquisar" type="button" class="btn btn-primary form-control" title="Botão de Pesquisa" onclick="PesquisaVndDia();">Buscar</button>
        </div>
    </div>
</form>
<br />

<div id="_tableLista">

</div>

<script>

    //chamo a função que passa os valores via JS e preenche a tabela quando abre a pagina
    PesquisaVndDia();
    function PesquisaVndDia() {

        var Parametro = {};
        Parametro.evento = $('#cbPesquisa option:selected').text();
        // Parametro.evento = $('#cbPesquisa').find(":selected").text();
        var par = JSON.stringify(Parametro)

        // preencho a grid Vendas Dia
        $.ajax({
            url: '@Url.Action("_Listar", "Home")',
            dataType: 'text',
            type: 'POST',
            data: { agendaListar: par },
            async: true,
            success: function (data) {
                $('#_tableLista').html(data);
            }
        });
    }

    function Deletar(Id) {
        $.ajax({
            url: '@Url.Action("Deletar","Home")',
            data: { Id: Id },
            dataType: "text",
            type: 'POST',
            async: true,
            success: function (data) {
                alert(data);
                PesquisaVndDia();
                //renderizar a partial view de novo

            }

        });
    }

</script>

PROJETO/Agenda/Agenda/Views/Home/_Listar.cshtml
@{
    System.Data.DataTable dt = (System.Data.DataTable)Session["AgendaLista"];
}

<div class="table table-responsive">
    <table class="table table-hover table-striped">
        <thead>
            <tr style="color: white; background-color:#1f8bb1; font: bold">
                <th class="text-left">Código Agendamento</th>
                <th class="text-left">Título Agendamento</th>
                <th class="text-left">Descrição Agendamento</th>
                <th class="text-left">Data Agendamento</th>
                <th class="text-left">Categoria</th>
                <th class="text-left">Excluir Agendamento</th>
            </tr>
        </thead>

        <tbody id="resultadoTabela">

            @foreach (System.Data.DataRow row in dt.Rows)
            {
               
                <tr style="line-height:25px;">
                    <td>@row["agendaId"].ToString()</td>
                    <td>@row["agendaTitulo"].ToString()</td>
                    <td>@row["agendaDescricao"].ToString()</td>
                    <td>@row["agendaData"].ToString()</td>
                    <td>@row["categoriaDescricao"].ToString()</td>
                    <td><button class="btn btn-danger" title="Excluir agendamento" onclick="Deletar(@row["agendaId"])">Deletar</button></td>
                </tr>
            }

        </tbody>
    </table>
</div>

PROJETO/Agenda/Agenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navBarTopo">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Agendamentos Realizados", "Listar", "Home")</li>
                    <li>@Html.ActionLink("Cadastrar Agendamento", "Cadastrar", "Home")</li>
                    <li>@Html.ActionLink("Cadastrar Categoria", "Inserir", "Categoria")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>